### ISSUE TITLE
Support for dask dataframes

### ISSUE THREAD

**Issue by eyadsibai** [ericmjl/pyjanitor#125]
Hi!

I was wondering if possible to support dask dataframe with this awesome package.

**Comment by ericmjl** [comment]
@eyadsibai, it entirely depends on Dask's ability to register functions! I would suggest posting upstream on the Dask project GitHub, to see if the pandas extension API is supported.

**Comment by zbarry** [comment]
@eyadsibai - in some cases, maybe this would work:

http://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.map_partitions

With this, I guess Dask spits out actual Pandas dataframes to your supplied function... as long as what you're trying to do with pyjanitor can work independently on separate partitions of the Dask dataframe, you should be good(?) Another option might be: http://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.to_delayed , and then operating on that list of `delayed` objects... something roughly like:

```
@dask.delayed
def something_with_pyjanitor(df):
    return df.func().func().func()

partitions = dask_df.to_delayed()

transformed_partitions = [something_with_pyjanitor(partition) for partition in partitions]

new_dask_df = dd.from_delayed(transformed_partitions)
```

Treat this as little more than pseudocode, haha.

Curious to know what happens if you try it out!

**Comment by zbarry** [comment]
Think this can be considered addressed for now.

**Comment by szuckerman** [comment]
I’ve been looking into Dask recently and it seems like this isn’t possible for Dask DataFrames, but there may be a workaround. 

Dask dataframes use Pandas but don’t copy all methods since some methods don’t work well with distributed systems (median, for example). I also don’t think that pandas_flavor works for Dask, even though they use pandas under the hood (due to the fact of the first issue of not copying all methods). 

However, that’s just on the DataFrame side of things. One can use the Dask client to run any python code in a distributed manner and could just run Dask on the pyjanitor code (I haven’t tried this though; just a guess). 

Similarly, one could do whatever work they need with pandas and pyjanitor and use the .from_pandas() method in Dask to convert it to a Dask DataFrame (albeit without the pyjanitor methods).
