### ISSUE TITLE
Tidy statsmodel with R broom functions

### ISSUE THREAD

**Issue by jcvall** [ericmjl/pyjanitor#157]
Started to create R broom like functions to statmodels for a few model types.  Is this something we can extend to pyjanitor?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zbarry** [comment]
Don't really have any experience with R. What would be the gist of what you're interested in adding?

**Comment by szuckerman** [comment]
I like the idea of adding stuff like this, but the issue is that it doesn’t make sense to return a DataFrame. 

For example, I could imagine someone would want to get some statistical information from a DataFrame (ex: p-values for certain columns) but it doesn’t make sense to store that in the main DataFrame object that’s being manipulated. 

I would propose the following:

Have a janitor.utils module that contains a dictionary for the relevant info. 

Someone could do:
from janitor.utils import stats

Which would add the functionality. The results would be stored in a dictionary in that module. The first parameter of the pyjanitor method would be the key in the dictionary. 

Something like this:

df.summary_stats(“df”)

stats_vals[“df”]

It wouldn’t be limited to statistics; it could open a lot of doors to summaries for the DataFrame. My validation proposal is another option.

**Comment by jcvall** [comment]
My thoughts on this:

1. This would work like the R Broom package.  This package take an output of the statistical model and puts it into a data frame format.  I have some examples here.

Blog on R Broom package - 
http://varianceexplained.org/r/broom-intro/

Word Doc of example thus far..
[Statsmodel – broom examples.docx](https://github.com/ericmjl/pyjanitor/files/3125358/Statsmodel.broom.examples.docx)

2. This could be an extension package like Finance and Chemistry perhaps?

3. I could get some of the core statsmodels set up like (OLS, GLM, OLS_Regularize, GLM_Regularize, ect...) and open it up to the sprints that Eric may be putting together for other models like time series and survival analysis for example.

Is it a worthy project?  I have been looking everywhere for something like this and the closest that I see is pybroom.  But this doesn't have statsmodel functionality and there seems to be a desire from the community for something like this.  Let me know what your are thinking...thanks.

**Comment by jcvall** [comment]
I might have been overly excited about this, and want to take a step back.  And for good reason.  Broom ( the R package) is very simple but useful package and I think would be a great addition
to pyjanitor.

It really is one of the most popular data science packages out there (I am not kidding).  I don't think I am doing it fair justice in my pitch, and this is total my fault.  I accept failure here.

The benefit of this package come from analyzing many models at once within the context of a data frame by grouping on the variables of interest and reviewing the results. For example...Here I took the titanic data set  and performed regression for three separate models by class on the ship.  
![Screen Shot 2019-04-29 at 8 48 02 PM](https://user-images.githubusercontent.com/20308031/56935671-93f3bc00-6ac0-11e9-821e-66a2eb58371e.png)

I think what I will do next, if it is alright, is present a more complete package with examples.  I just want a chance to give this idea a fair chance.

**Comment by szuckerman** [comment]
This looks super awesome. Since there’s so much functionality do you think it might be better to develop it as its own package that will integrate with pyjanitor?

**Comment by jcvall** [comment]
I have given that a thought.  And since I am writing the scripts anyway I wouldn't mind making its own package. I will close this for now.  If there is any interest in the future let me know.

**Comment by raerickson** [comment]
@jcvall Did you ever create a package?
