### ISSUE TITLE
Update one of the "outputs" in examples/notebooks/dirty_data.ipynb

### ISSUE THREAD

**Issue by Eidhagen** [ericmjl/pyjanitor#208]
In the example where a empty row is removed (cell 5), change the print statement so the rows that surround the removed row is shown instead of just the five rows in the top of the dataframe. By doing this it will be clearer to the reader what actually happened.

**Comment by ericmjl** [comment]
@Eidhagen thanks for raising this! I think this will not be necessary any more, because we've moved the example into a notebook that is being built on readthedocs. I'm figuring out how to build `dev` on readthedocs right now!

**Comment by ericmjl** [comment]
I went back in this morning and looked at the notebooks. The issue is still relevant, but now applies to the notebooks instead of `example.rst`. I will mark this as available to hack on, and edit the issue appropriately.

Because you've already done a contrib yesterday to the docs, I'm happy for others to tackle this one!
