### ISSUE TITLE
Linting issue in Makefile

### ISSUE THREAD

**Issue by dendrondal** [ericmjl/pyjanitor#234]
When trying to run Make Check with my most recent PR, two errors were found. The first is a relatively easy fix due to a deprecated term in isort, the second isn't one I really know how to google the solution for. After the pycodestyle . is run, the following stacktrace is dumped:

```
./janitor/functions.py:466:80: E501 line too long (111 > 79 characters)
./janitor/functions.py:467:80: E501 line too long (117 > 79 characters)
./janitor/functions.py:1191:1: W293 blank line contains whitespace
./janitor/functions.py:1193:80: E501 line too long (82 > 79 characters)
./janitor/functions.py:1194:80: E501 line too long (81 > 79 characters)
./janitor/functions.py:1194:82: W291 trailing whitespace
./janitor/functions.py:1222:13: E722 do not use bare 'except'
./janitor/functions.py:1225:69: E262 inline comment should start with '# '
./janitor/functions.py:2692:80: E501 line too long (93 > 79 characters)
make: *** [lint] Error 1
```
The "checks complete" doesn't actually echo. I assume the E501, E722, 262, etc. are what is causing this vague message to be thrown, but why isn't black catching this?

**Comment by ericmjl** [comment]
My current guess is that black isn't formatting the docstrings, which, if I remember correctly, is an intentional design choice by the black devs. 

Only E722 is one that we may want to look at.

As for the others, modifying the docstrings might be the most productive thing to do here. I will file an issue related to this one.
