### ISSUE TITLE
Take ideas/code from Agate?

### ISSUE THREAD

**Issue by yozlet** [ericmjl/pyjanitor#34]
Speaking as a newcomer to Pandas who finds its syntax confusing, pyjanitor is a breath of fresh air. There's a similar, older project which may provide extra inspiration, maybe even code: [agate](https://agate.readthedocs.io/en/1.6.1/api.html) by @onyxfish (who also created the fantastic [Quartz guide to bad data](https://github.com/Quartz/bad-data-guide)). However, he now seems to have moved on to other things, and development has been considerably slower for the past couple of years.

Agate is well worth a look: the documentation is extensive and well-written, and it has a few features which pyjanitor doesn't (yet). Unfortunately much of the code may be hard to port as it relies on its own table implementation rather than using Pandas DataFrame or similar. Even so, it's worth checking out.

**Comment by ericmjl** [comment]
Thanks for pinging in, @yozlet! I've added the reference tag to this thread so that myself and others can come back to it later.

You mentioned that agate has a few features not implemented by pyjanitor. I'd love to see them implemented, if they fit the criteria for a method-chain-able API. Would you be open to listing them specifically below, so that we have an openly-available checklist? It would help others who would like to contribute to pyjanitor.

**Comment by ericmjl** [comment]
@yozlet closing this issue for now. Please feel free to reopen.

**Comment by yozlet** [comment]
Thanks @ericmjl, and sorry for not replying earlier - I've been swamped. If I see particular methods I want from Agate, I'll file individual issues.
