### ISSUE TITLE
[ENH] pivot_wider() and pivot_longer()

### ISSUE THREAD

**Issue by benjaminjack** [ericmjl/pyjanitor#434]
# Brief Description

Pandas has several functions for pivoting. The `melt` function takes a 'wide' dataframe and makes it 'long', and `pivot_table` takes a 'long' dataframe and makes it 'wide'. Similarly, `stack` and `unstack` perform pivot operations using multilevel indices. Tom Augspurger explains all of the pandas pivoting functions in his [Modern Pandas guide](https://tomaugspurger.github.io/modern-5-tidy). If you look through his guide, you can see that the API for these four functions are all different and difficult to remember.

I would like to propose `pivot_wider` and `pivot_longer` functions inspired by functions in the R [tidyr package](https://tidyr.tidyverse.org/dev/articles/pivot.html). These functions are pure syntactic sugar around pandas `melt` and `unpivot`. They should have consistent APIs, and they should be symmetric. That is, you should be able to take a 'wide' dataframe, pass it through `pivot_longer`, then pass it through `pivot_wider` to get back to the exact same 'wide' dataframe that we started with.

# Example API

Imagine that we have a 'wide' table of heartrate data for patients treated under two different drugs, *a* and *b*.

| name | a | b |
| --- | --- | --- |
| Wilbur | 67 | 56 |
| Petunia | 80 | 90 |
| Gregory | 64 | 50 |

Here's how we would convert this to a 'long' table.

```python
df.pivot_longer(column_names=['a', 'b'], names_to=['drug'], values_to=['heartrate'])
```

The output would be a 'long' table that look like this.

| name | drug | heartrate |
|---|---|---|
| Wilbur | a   |     67  |
| Petunia |   a  |      80 |
| Gregory |   a  |      64 |
| Wilbur  |   b   |    56 |
| Petunia |    b  |    90 |
| Gregory  |  b   |     50 | 

Now we'll take the above table and transform it back into a 'wide' table using `pivot_wider`.

```python
df.pivot_wider(names_from=['drug'], values_from=['heartrate'])
```

And now we're back to our 'wide' table:

| name | a | b |
| --- | --- | --- |
| Wilbur | 67 | 56 |
| Petunia | 80 | 90 |
| Gregory | 64 | 50 |

I would love some feedback on the API before I start implementing this in code!

**Comment by benjaminjack** [comment]
I’m also happy to work on this issue!

**Comment by szuckerman** [comment]
I think this is a great idea! `value_name` and `value_vars` sometimes gets confusing and I think this is more clear. However the best part is that in Pandas these are external functions from the `DataFrame`; they're module-level (`pd.melt`, `pd.pivot_table`). This would be great to add to the method-chaining syntax.

Also, to see the difference, below is the same code above implemented in standard Pandas:

```python

import pandas as pd

name = ['Wilbur', 'Petunia', 'Gregory']
a = [67, 80, 64]
b = [56, 90, 50]

dat = pd.DataFrame({'name': name, 'a': a, 'b': b})

long_dat = pd.melt(dat.reset_index(), id_vars='name', value_vars=['a', 'b'], value_name='heartrate').rename(columns={'variable': 'drug'})

wide_dat = pd.pivot_table(long_dat.reset_index(), values='heartrate', index=['name'], columns=['drug']).reset_index()
```

The automatic column renaming definitely nice and can get annoying using the standard version.

One thing to think about, though, is how indicies will work. I did a `reset_index()` which is probably what you want, but still something to think about. Similarly, when using `pd.pivot_table` the index gets named to `drug`. Not sure what you think about having a named index.

**Comment by ericmjl** [comment]
I'm in agreement with @szuckerman here. This looks good, @benjaminjack! Don't forget to add tests and docstring :smile:.

**Comment by benjaminjack** [comment]
Thanks for all the feedback so far! I took a first pass at implementation, docs, and tests for `pivot_longer` here: https://github.com/benjaminjack/pyjanitor/commit/e3df817903c20dd21634461c8a92aec137963ed0

A few questions:
1. How should we handle indexes? Right now I'm just resetting the index before `pd.melt`. This may cause problems with multilevel indexes though.
2. Any guidance on using Hypothesis for unit testing? Is it necessary here? I have not used Hypothesis before.
3. What's best practice for error-handling? Catch any errors from the underlying `pd.melt` and generate more user-friendly errors? Or leave as is?

**Comment by ericmjl** [comment]
Whoa, @benjaminjack, it looks like I let this ball drop. Many apologies! I didn't mean to, I think I opened up the issue, read it, but didn't have enough time to think carefully about your questions, and then left to do something else.

Let me try addressing the questions, having read your branch's latest commit.

> How should we handle indexes? Right now I'm just resetting the index before pd.melt. This may cause problems with multilevel indexes though.

In this case, I am quite sure that resetting the index is the correct thing to do. I'm not sure how to explain my reasoning, though, as I'm struggling to find the words to describe it, so I'm right now being guided by intuition. 

If you're feeling unsure about it, I think it's not an issue to add a `reset_index=True` kwarg. I am tempted to add that for the `.shuffle()` function, and leave it on by default, because again, that intuitively sounds like the right thing to do.

> Any guidance on using Hypothesis for unit testing? Is it necessary here? I have not used Hypothesis before.

Hypothesis is usually the "next step up" from example-based testing. I want to keep the contribution barrier low, so I have never historically required a Hypothesis-generated test. If you're feeling adventurous, feel free to do so, but do know that an example-based test is sufficient.

> What's best practice for error-handling? Catch any errors from the underlying pd.melt and generate more user-friendly errors? Or leave as is?

I think user-friendly errors are great! They help not only end-users, but also us maintainers, as it's quite explicit and clear as to what is being caught. That said, don't feel pressured to handle it all; we can always leave this as a new issue that a newcomer can tackle.

-----

Aside from that, @benjaminjack, I'd encourage you to put in the PR even if it's not done! You can put a [WIP] in the PR title, and that will signal to me that it's not ready for merging (I also have a WIP bot that serves as a second check.) You can continually update the PR with new commits; they automatically get tacked on. 

If you put in the PR, that'll also keep the issue visible in my mind, as I check the PR tab more than the issue tracker 😂.

**Comment by ericmjl** [comment]
@benjaminjack given the inactivity here, I will release this issue back into the pool of “available for hacking” issues. Hope you’re ok with that! If you’d like to take it on later, please feel free to ping back here! :smile:

**Comment by ericmjl** [comment]
@benjaminjack I took a second look at the code that you had written. It's got very good documentation, and I would be loathe to claim that work as my own. Would you be interested in re-opening the PR?

**Comment by samukweku** [comment]
@ericmjl , If this is still available, kindly assign to me.

**Comment by ericmjl** [comment]
@samukweku assigning! If possible, please use as much as you can salvage from @benjaminjack’s PR, and include him in the changelog entry! Sharing the work/credit keeps things encouraging for everyone involved.

**Comment by samukweku** [comment]
@ericmjl , how do I access @benjaminjack PR?

**Comment by ericmjl** [comment]
@samukweku I realized I didn't explicitly link what @benjaminjack's PR was. Here it is: https://github.com/benjaminjack/pyjanitor/commit/e3df817903c20dd21634461c8a92aec137963ed0
