### ISSUE TITLE
[ENH] Empirical CDF calculation

### ISSUE THREAD

**Issue by zbarry** [ericmjl/pyjanitor#583]
Because @ericmjl & I keep copypasta'ing it across all my notebooks

```python
def calc_single_ecdf(data):
    """Compute the Empirical Cumulative Distribution Function for an Array."""
    # Number of points n
    n = len(data)

    # x data for the CDF 
    x = np.sort(data)

    # y data for the CDF
    y = np.arange(1, n + 1 ) / n

    return x, y
```

**Comment by jiafengkevinchen** [comment]
Does this handle NaNs correctly? I think the denominator should be notnull.sum() right?

**Comment by ericmjl** [comment]
@jiafengkevinchen yes, the function can be improved to handle nulls. There shouldn't be a sum, though; an ECDF displays cumulative fraction of points that are at or below a given value. Either there should be a check for no nulls in `data`, or we drop nulls automagically. I'm leaning to dropping nulls automagically, for this means setting a sane default on the data.

**Comment by jiafengkevinchen** [comment]
> @jiafengkevinchen yes, the function can be improved to handle nulls. There shouldn't be a sum, though; an ECDF displays cumulative fraction of points that are at or below a given value. Either there should be a check for no nulls in `data`, or we drop nulls automagically. I'm leaning to dropping nulls automagically, for this means setting a sane default on the data.

Incidentally, I think there's an ECDF function in statsmodels, but it also doesn't handle nulls correctly. Since ECDFs are easy to compute, we should just code it up like the suggested implementations

**Comment by ericmjl** [comment]
Looping back on this issue. I've been thinking about semantically useful behaviour for this function.

I think it should be part of the `math.py` module, and be made a pandas Series function, much like the other functions in `math.py`. This is because it operates on taking in a single column of data. 

In that way, we can write code that looks like the following:

```python
df = pd.DataFrame(...)

x, y = df["column_name"].ecdf()
plt.scatter(x, y)
```

I expect that that this kind of use case would probably be the place where such a function would be most useful.
