### ISSUE TITLE
Feature enhancement: collapsing MultiIndex columns

### ISSUE THREAD

**Issue by zbarry** [ericmjl/pyjanitor#61]
For example, after aggregation with multiple functions.

For `df` with columns `['group', 'category', 'value']`:

```python
stats_df = (
    df.groupby(['group', 'category'])
    .agg(['mean', 'median'])
    .reset_index()
)
```

produces `stats_df` with a `MultiIndex` `.columns` attribute where `{'mean', 'median'}` are second level column names under `value`. It would be nice if `.columns` was just an `Index` instead, for some applications.

Now, to flatten the `MultiIndex` out into an `Index` by concatenating the different levels with an underscore:

`stats_df.columns.values` is `array([('group', ''), ('category', ''), ('value', 'mean'), ('value', 'median')], dtype=object)`

`stats_df.columns = ['_'.join(tup) if tup[1] != '' else tup[0] for tup in stats_df.columns.values]`

`stats_df.columns` is now `['group', 'category', 'value_mean', 'value_median']`

**Comment by ericmjl** [comment]
@zbarry thanks for putting this in! I'm sure it'll be a valuable addition. 

I did a second thought on the name of the function, and it may or may not be the most inclusive/accessible one for non-native English speakers. At first glance, I can't think of a better name, but if I can see one, I'll ping back on the PR to suggest it. Otherwise, please feel free to run with `collapse_levels()`.

**Comment by zbarry** [comment]
Sounds good. I was basing the name on [droplevel](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.MultiIndex.droplevel.html). Maybe a different word than collapse, then?

**Comment by ericmjl** [comment]
Maybe so. For now, `collapse_levels` should be fine, if paired with a good docstring. But don't sweat it for now. :smile:
