### ISSUE TITLE
API Documentation not functioning properly

### ISSUE THREAD

**Issue by samukweku** [ericmjl/pyjanitor#629]
The API documentation page is not working properly, there are no links to individual function pages, and there are no descriptions for the functions either. I checked via PC and phone, same thing.

**Comment by ericmjl** [comment]
@samukweku this is a good catch, thanks for flagging this! I will look into it today.

**Comment by ericmjl** [comment]
First off, here's a screenshot of the current docs, to verify the problem that @samukweku reported.

![Screenshot from 2020-02-04 21-59-37](https://user-images.githubusercontent.com/2631566/73807251-c3470000-4799-11ea-910b-00fa533577df.png)

Hmmm, I'm struggling to find the root cause of the problem. To begin, I tried building the docs locally, and everything builds correctly. Screenshot:

![Screenshot from 2020-02-04 22-00-45](https://user-images.githubusercontent.com/2631566/73807263-cfcb5880-4799-11ea-910b-a520fc4ffc33.png)

What this tells me is that I have to look for the difference between the readthedocs build and the local build.

**Comment by ericmjl** [comment]
I have moved the docs onto [GitHub pages instead](https://ericmjl.github.io/pyjanitor). Readthedocs was good for getting started, but I suspect we might have done something too custom for the readthedocs build environment. Meanwhile, the docs build perfectly on GitHub pages.

**Comment by ericmjl** [comment]
@samukweku, I'm going to close this issue for now. Hope this helps.
