### ISSUE TITLE
"as_categorical"

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#677]
Another idea!

```python
@pf.register_dataframe_method
def as_categorical(df, column_name, categories=None, ordered=True):
    """
    Convert one column in the dataframe to a categorical one.
    """
    if categories is None:
        categories = sorted(df[column_name].unique())
    df[column_name] = pd.Categorical(
        df[column_name], categories=categories, ordered=ordered,
    )
    return df
```

It replaces repeatedly doing this piece:

```python
df[column_name] = pd.Categorical(
    df[column_name], categories=categories, ordered=ordered,
)
```

Leaving this here for now.

**Comment by szuckerman** [comment]
Looks good; just two ideas to add which immediately come to mind:

1.) what happens if the “categories” iterator doesn’t match the values in the column? Warning? Error? 

2.) maybe also have a default of categories=set(df[column]) so that users don’t need to input manually, but in that case ordered would need to be False.

**Comment by eyaltrabelsi** [comment]
@ericmjl another small point is that the sort is only needed if the ordered is passed
