### ISSUE TITLE
Fix default pandas methods

### ISSUE THREAD

**Issue by shantanuo** [ericmjl/pyjanitor#70]
Is it possible to "fix" pandas methods using pyjanitor? For e.g. I will like to validate the parameters for read_excel or read_csv. I have raised an issue but there is no progress.

https://github.com/pandas-dev/pandas/issues/22189

If janitor accept the PR to override the default behavior of read methods, then it will be great.

**Comment by ericmjl** [comment]
> Is it possible to "fix" pandas methods using pyjanitor? ... If janitor accept the PR to override the default behavior of read methods, then it will be great.

@shantanuo I'd be inclined to disagree with doing that. The purpose behind pyjanitor is to provide the convenience APIs that pandas did not provide. If there's a bug that's inside pandas, then that should be raised with the pandas devs, as you did already.

**Comment by Zsailer** [comment]
I agree with @ericmjl here. 

pyjanitor aims to be a general purpose library that extends the Pandas API. Users should be able to add pyjanitor to their current workflow without breaking their existing code.

If pyjanitor starts patching pandas functions/methods, it could quickly cause trouble for users and prevent them from using pyjanitor. 

Also, I don't think you need a sophisticated tool like pyjanitor to fix your problems. Because `read_csv`, `read_excel` are just functions, you could create a small module that enforces the signature you want:

```python
import pandas as pd
from functools import wraps

@wraps(pd.read_excel)
def read_excel(parameters_that_you_want):
    # Only include the parameters you want in the function signature.
    return pd.read_excel(parameters_that_you_want)
```
Perhaps this would solve your problem until Pandas addresses the issue?
