### ISSUE TITLE
Forward/Backward Fill

### ISSUE THREAD

**Issue by samukweku** [ericmjl/pyjanitor#700]
# Brief Description

I would like to propose a forward/backward fill method, similar to ``fill`` in tidyr. In Pandas, forward/backward fill can be achieved, but you cannot select directions for different columns within a dataframe.

# Example API
    @pf.register_dataframe_method
    def fill(df, columns = ..., directions = sequence of directions(up, down, updown, downup):
        """
        Forward or backward fill on a column or columns of a dataframe.
        """
        df[column] = df[column].ffill() #forward fill will be the default
        return df

```python
example data : 
df = pd.DataFrame(data={'a':[1,2,3,None],'b':[4,5,None,6],'c':[None,None,7,8]})

          a	b	c
0	1.0	4.0	NaN
1	2.0	5.0	NaN
2	3.0	NaN	7.0
3	NaN	6.0	8.0

#downward fill (backward fill in Pandas) on only the `a` column:
df.fill(columns="a", directions = "down")

# downward fill on  ``a``, upward fill on  ``c`` :

# the idea is the directions will be paired with the columns
# similar to what exists when sorting multiple columns in Pandas' sort_values 
# with booleans passed to the ``ascending`` argument
df.fill(columns=["a", "c"], directions = ["down", "up"])



# currently in Pandas, ffill and bfill are applied to all the columns that have null values, 
# you cannot select which columns to be forward or backward filled.
```

Still undecided on the name, as I do not feel it clearly conveys what it should do without reading the function description.

**Comment by ericmjl** [comment]
@samukweku I like the idea! I’ve had to use filling before, and the lack of a dataframe-attached API made things just a _tad_ more complicated.

**Comment by samukweku** [comment]
Glad to know it could be useful to others as well. I would love to work on it, but still need opinions from others as well, especially with the name. Maybe someone has something better?

**Comment by ericmjl** [comment]
To me, the function name `fill` sounds about right. The argument options could possibly use additional eyes.

I can see where the "up" and "down" comes from - it is natural to look at a table and say "fill upwards" vs. "fill downwards". 

At the same time, pandas has the "forward fill" and "backward fill", which I think come from time series analysis. There, forward corresponds to "fill downwards", because it is usually assumed that time axis flows top to bottom. 

I guess it's a matter of choosing one set of semantic conventions, sticking with it, and documenting other possible conventions to educate users?
